name: Docker Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - infra/atlantis
    paths-ignore:
      - .gitignore

jobs:
  call-workflow-passing-data:
    uses: lytxinc/lytx-workflows/.github/workflows/reusable-dockerfile-test-build.yml@master
    with:
      image_name: atlantis
