---
name: Docker Build

on:
  pull_request:
    paths:
      - 'k8s/atlantis/**'

jobs:
  call-workflow-passing-data:
    uses: lytxinc/lytx-workflows/.github/workflows/reusable-dockerfile-test-build.yml@set-context
    with:
      image_name: atlantis
      image_context: './k8s/atlantis'
