name: Docker Build

on:
  push:
    branches:
      - main
    paths:
      - infra/atlantis

jobs:
  call-workflow-passing-data:
    uses: lytxinc/lytx-workflows/.github/workflows/reusable-dockerfile-test-build.yml@master
    with:
      image_name: atlantis
