---
name: Docker Push

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/atlantis/**'

jobs:
  call-workflow-passing-data:
    uses: lytxinc/lytx-workflows/.github/workflows/reusable-dockerfile-build-push.yml@master
    with:
      image_name: atlantis
      IMAGE_CONTEXT: "./k8s/atlantis"
      SLACK_CHANNEL: "lytx-cloud-infrastructure-notifications"
